plugins {
    id 'multiloader-loader'
    id 'net.minecraftforge.gradle' version '[7,8)'
    id 'net.darkhax.curseforgegradle'
    id "com.modrinth.minotaur"
}

minecraft {
    mappings channel: 'official', version: minecraft_version
    runs {
        configureEach {
            workingDir.convention layout.projectDirectory.dir('run')
            // Mixin requires either specifying the config via command line, or in the Manifest
            args "--mixin.config=${mod_id}.mixins.json"
            args "--mixin.config=${mod_id}.forge.mixins.json"
        }
        register('client') {
            systemProperty 'forge.enabledGameTestNamespaces', mod_id
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

apply from: rootProject.file('repositories.gradle')
repositories {
    maven minecraft.mavenizer
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
}

dependencies {
    def mcVersion = minecraft_version
    def forgeVersion = forge_version
    implementation minecraft.dependency("net.minecraftforge:forge:$mcVersion-$forgeVersion")
}
apply from: 'dependencies.gradle'

task curseforge(type: net.darkhax.curseforgegradle.TaskPublishCurseForge) {
    dependsOn('build')
    description = 'Publishes the Forge build to CurseForge.'
    group = 'publishing'

    apiToken = project.findProperty("curseforge.api_key") ?: System.getenv("CURSEFORGE_TOKEN") ?: "none"

    def mainFile = upload(curseforge_project_id, jar.archiveFile.get().asFile)
    mainFile.changelog = rootProject.file('CHANGELOG.md').text
    mainFile.addRequirement("balm")
    project.minecraft_versions.split(',').toList().each { mainFile.addGameVersion(it) }
    mainFile.releaseType = "release"
    project.findProperty("curseforge_environments")?.split(",")?.toList()?.each { mainFile.addEnvironment(it) }
}

modrinth {
    token = project.findProperty("modrinth.token") ?: System.getenv("MODRINTH_TOKEN") ?: "none"
    projectId = project.modrinth_project_id
    versionType = project.modrinth_release_type
    versionNumber = project.version + "+forge-" + project.minecraft_version
    uploadFile = jar
    changelog = rootProject.file("CHANGELOG.md").text
    gameVersions = project.minecraft_versions.split(',').toList()
    syncBodyFrom = rootProject.file("modpage.md").text
    loaders = ['forge']
    dependencies {
        required.project "balm"
    }
}
