name: validate-lang
on:
  push:
    branches:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+'

jobs:
  validate-lang:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Validate language files
        uses: TwelveIterations/validate-minecraft-lang@v1
